extends GutTest
class_name ECSComponentFactoryTest

func test_known_types() -> void:
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_BYTE))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_INT64))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_INT32))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_FLOAT64))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_FLOAT32))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_VECTOR2))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_VECTOR3))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_VECTOR4))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_COLOR))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_STRING))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.BOOL))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.INT))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.FLOAT))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.AABB))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.RECT2))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.BASIS))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PLANE))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.TRANSFORM2D))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.TRANSFORM3D))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.QUATERNION))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR2))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR2I))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR3I))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR3))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR4I))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR4))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.COLOR))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.STRINGNAME))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.STRING))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.NODEPATH))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.RID))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.RESOURCE))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_SCENE))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.NODE))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.NODE2D))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.NODE3D))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.OBJECT))
	assert_not_null(ECSComponentFactory.create_component(ECSComponent.Type.REFCOUNTED))

func test_storage_classes() -> void:
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_VECTOR2) is ECSComponentPackedVector2Array)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.PACKED_STRING) is ECSComponentPackedStringArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.AABB) is ECSComponentAABBArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.PLANE) is ECSComponentPlaneArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.VECTOR2) is ECSComponentVector2Array)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.COLOR) is ECSComponentColorArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.STRING) is ECSComponentStringArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.STRINGNAME) is ECSComponentStringNameArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.NODEPATH) is ECSComponentNodePathArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.RID) is ECSComponentRIDArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.OBJECT) is ECSComponentObjectArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.NODE2D) is ECSComponentNode2DArray)
	assert_true(ECSComponentFactory.create_component(ECSComponent.Type.RESOURCE) is ECSComponentResourceArray)

func test_invalid_type_returns_null() -> void:
	assert_null(ECSComponentFactory.create_component(999 as ECSComponent.Type))
	assert_push_error("unsupported component type")
